spring:
  profiles:
    active: ${APP_ENV:development}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost/blog}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secret}
  jpa:
    open-in-view: false
  flyway:
    locations: classpath:/db/migration, classpath:/db/seeders
